GET http://localhost:5000/styles

###

GET http://localhost:5000/styles/61642482-06d2-42f6-9b7d-dc56ac094b22

###
POST http://localhost:5000/styles
Content-Type: application/json

{
    "name": "target2",
    "type": "bible",
    "targets": [
        {
            "styleId": "22d49ae3-2016-487a-9fe3-5dd230d9790a",
            "targetId": "0d1bd2ae-54d8-400d-adaf-72bbc8152866",
            "classes": "w-full"
        }
    ]
}


###
PUT http://localhost:5000/styles/75736f84-3e86-4ac5-a718-743211962b12
Content-Type: application/json

{
    "name": "bibliaBolada",
    "type": "bible",
    "targets": [
        {
            "styleId": "22d49ae3-2016-487a-9fe3-5dd230d9790a",
            "targetId": "0d1bd2ae-54d8-400d-adaf-72bbc8152866",
            "classes": "w-full"
        }
    ]
}

###
DELETE http://localhost:5000/styles/034c8456-1315-4aa3-8b01-eaed8f86ac8d
Content-Type: application/json


###

GET http://localhost:5000/styles/active/music
Content-Type: application/json

###

POST http://localhost:5000/styles/active
Content-Type: application/json

{
    "code": "bible",
    "styleId": "909891e3-e1e0-4204-93de-adbc9129b2e1"
}

###
GET http://localhost:5000/styles/target?type=bible

